//src/constants/studentConstants.js

export const STUDENT_CREATE_REQUEST = 'STUDENT_CREATE_REQUEST'
export const STUDENT_CREATE_SUCCESS = 'STUDENT_CREATE_SUCCESS'
export const STUDENT_CREATE_FAIL = 'STUDENT_CREATE_FAIL'

export const STUDENT_LIST_REQUEST = 'STUDENT_LIST_REQUEST'
export const STUDENT_LIST_SUCCESS = 'STUDENT_LIST_SUCCESS'
export const STUDENT_LIST_FAIL = 'STUDENT_LIST_FAIL'

export const STUDENT_DETAILS_REQUEST = 'STUDENT_DETAILS_REQUEST'
export const STUDENT_DETAILS_SUCCESS = 'STUDENT_DETAILS_SUCCESS'
export const STUDENT_DETAILS_FAIL = 'STUDENT_DETAILS_FAIL'

export const STUDENT_UPDATE_REQUEST = 'STUDENT_UPDATE_REQUEST'
export const STUDENT_UPDATE_SUCCESS = 'STUDENT_UPDATE_SUCCESS'
export const STUDENT_UPDATE_FAIL = 'STUDENT_UPDATE_FAIL'

export const STUDENT_DELETE_REQUEST = 'STUDENT_DELETE_REQUEST'
export const STUDENT_DELETE_SUCCESS = 'STUDENT_DELETE_SUCCESS'
export const STUDENT_DELETE_FAIL = 'STUDENT_DELETE_FAIL'

export const STUDENT_DELETE_ALL_REQUEST = 'STUDENT_DELETE_ALL_REQUEST'
export const STUDENT_DELETE_ALL_SUCCESS = 'STUDENT_DELETE_ALL_SUCCESS'
export const STUDENT_DELETE_ALL_FAIL = 'STUDENT_DELETE_ALL_FAIL'

export const STUDENT_SEARCH_REQUEST = 'STUDENT_SEARCH_REQUEST'
export const STUDENT_SEARCH_SUCCESS = 'STUDENT_SEARCH_SUCCESS'
export const STUDENT_SEARCH_FAIL = 'STUDENT_SEARCH_FAIL'
